// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFile(arg1:string):Promise<main.WatchEntry>;

export function GetWatches():Promise<Array<main.WatchEntry>>;

export function RemoveWatch(arg1:number):Promise<void>;

export function SelectAndAddFile():Promise<main.WatchEntry>;

export function SetEnabled(arg1:number,arg2:boolean):Promise<void>;
