// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1) {
  return window['go']['main']['App']['AddFile'](arg1);
}

export function GetAPIBaseURL() {
  return window['go']['main']['App']['GetAPIBaseURL']();
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetRemoteChangeLog() {
  return window['go']['main']['App']['GetRemoteChangeLog']();
}

export function GetRunInTrayOnStartup() {
  return window['go']['main']['App']['GetRunInTrayOnStartup']();
}

export function GetSocketURL() {
  return window['go']['main']['App']['GetSocketURL']();
}

export function GetWatches() {
  return window['go']['main']['App']['GetWatches']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RemoveWatch(arg1) {
  return window['go']['main']['App']['RemoveWatch'](arg1);
}

export function SaveAPIKey(arg1) {
  return window['go']['main']['App']['SaveAPIKey'](arg1);
}

export function SelectAndAddFile() {
  return window['go']['main']['App']['SelectAndAddFile']();
}

export function SetEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetEnabled'](arg1, arg2);
}

export function SetRunInTrayOnStartup(arg1) {
  return window['go']['main']['App']['SetRunInTrayOnStartup'](arg1);
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}
